version: '2'
services:
  pomodorify-backend:
    build:
      context: .
    environment:
      NODE_ENV: development
      DB_HOST: db
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - .:/home/app/sensors-management
      - /home/app/sensors-management/node_modules
  db:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sensors_management
